name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Test
        run: go test -v .
